version: '3.1'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/dev/nginx.docker
    ports:
      - '8082:8080'
    volumes:
      - .:/var/www
      - ./docker/dev/nginx/ssl:/etc/nginx/ssl
    networks:
      - velmie_wallet_network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: docker/dev/php-fpm.docker
    volumes:
      - ./:/var/www
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=mysql'
    networks:
      - velmie_wallet_network

  mysql:
    image: mysql:5.7
    volumes:
        - ./storage/docker/mysql:/var/lib/mysql
    environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_USER=app"
        - "MYSQL_PASSWORD=secret"
        - "MYSQL_DATABASE=app"
    ports:
        - "33062:3306"
    networks:
      - velmie_wallet_network

networks:
  velmie_wallet_network:
