<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customization.proto

namespace Velmie\Wallet\Customization;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>velmie.wallet.customization.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.velmie.wallet.customization.Customization customization = 1;</code>
     */
    protected $customization = null;
    /**
     * Generated from protobuf field <code>.velmie.wallet.customization.Error error = 2;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Velmie\Wallet\Customization\Customization $customization
     *     @type \Velmie\Wallet\Customization\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Customization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.velmie.wallet.customization.Customization customization = 1;</code>
     * @return \Velmie\Wallet\Customization\Customization
     */
    public function getCustomization()
    {
        return $this->customization;
    }

    /**
     * Generated from protobuf field <code>.velmie.wallet.customization.Customization customization = 1;</code>
     * @param \Velmie\Wallet\Customization\Customization $var
     * @return $this
     */
    public function setCustomization($var)
    {
        GPBUtil::checkMessage($var, \Velmie\Wallet\Customization\Customization::class);
        $this->customization = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.velmie.wallet.customization.Error error = 2;</code>
     * @return \Velmie\Wallet\Customization\Error
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>.velmie.wallet.customization.Error error = 2;</code>
     * @param \Velmie\Wallet\Customization\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Velmie\Wallet\Customization\Error::class);
        $this->error = $var;

        return $this;
    }

}

