<?php
# Generated by the protocol buffer compiler (protoc-gen-twirp_php ).  DO NOT EDIT!
# source: customization.proto

declare(strict_types=1);

namespace Velmie\Wallet\Customization;

/**
 *
 *
 * Generated from protobuf service <code>velmie.wallet.customization.CustomizationHandler</code>
 */
interface CustomizationHandler
{
    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.customization.CustomizationHandler/GetByKey</code>
     *
     * @throws \Twirp\Error
     */
    public function GetByKey(array $ctx, \Velmie\Wallet\Customization\Request $req): \Velmie\Wallet\Customization\Response;
}
