<?php
# Generated by the protocol buffer compiler (protoc-gen-twirp_php ).  DO NOT EDIT!
# source: notifications.proto

declare(strict_types=1);

namespace Velmie\Wallet\Notifications;

/**
 *
 *
 * Generated from protobuf service <code>velmie.wallet.notifications.NotificationHandler</code>
 */
interface NotificationHandler
{
    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.notifications.NotificationHandler/Dispatch</code>
     *
     * @throws \Twirp\Error
     */
    public function Dispatch(array $ctx, \Velmie\Wallet\Notifications\Request $req): \Velmie\Wallet\Notifications\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.notifications.NotificationHandler/GetSettings</code>
     *
     * @throws \Twirp\Error
     */
    public function GetSettings(array $ctx, \Velmie\Wallet\Notifications\SettingsRequest $req): \Velmie\Wallet\Notifications\SettingsResponse;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.notifications.NotificationHandler/GetUserSettings</code>
     *
     * @throws \Twirp\Error
     */
    public function GetUserSettings(array $ctx, \Velmie\Wallet\Notifications\UserSettingsRequest $req): \Velmie\Wallet\Notifications\UserSettingsResponse;
}
