<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto

namespace Velmie\Wallet\Notifications;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>velmie.wallet.notifications.UserSettingsResponse</code>
 */
class UserSettingsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.notifications.UsersSetting userSettings = 1;</code>
     */
    private $userSettings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Velmie\Wallet\Notifications\UsersSetting[]|\Google\Protobuf\Internal\RepeatedField $userSettings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Notifications::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.notifications.UsersSetting userSettings = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserSettings()
    {
        return $this->userSettings;
    }

    /**
     * Generated from protobuf field <code>repeated .velmie.wallet.notifications.UsersSetting userSettings = 1;</code>
     * @param \Velmie\Wallet\Notifications\UsersSetting[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Velmie\Wallet\Notifications\UsersSetting::class);
        $this->userSettings = $arr;

        return $this;
    }

}

