<?php
# Generated by the protocol buffer compiler (protoc-gen-twirp_php ).  DO NOT EDIT!
# source: users.proto

declare(strict_types=1);

namespace Velmie\Wallet\Users;

/**
 *
 *
 * Generated from protobuf service <code>velmie.wallet.users.UserHandler</code>
 */
interface UserHandler
{
    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByUID</code>
     *
     * @throws \Twirp\Error
     */
    public function GetByUID(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByUsername</code>
     *
     * @throws \Twirp\Error
     */
    public function GetByUsername(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByProfileData</code>
     *
     * @throws \Twirp\Error
     */
    public function GetByProfileData(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByRoleName</code>
     *
     * @throws \Twirp\Error
     */
    public function GetByRoleName(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/ValidateAccessToken</code>
     *
     * @throws \Twirp\Error
     */
    public function ValidateAccessToken(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByUIDs</code>
     *
     * @throws \Twirp\Error
     */
    public function GetByUIDs(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByUserGroupId</code>
     *
     * @throws \Twirp\Error
     */
    public function GetByUserGroupId(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetAll</code>
     *
     * @throws \Twirp\Error
     */
    public function GetAll(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetFullUsersByUIDs</code>
     *
     * @throws \Twirp\Error
     */
    public function GetFullUsersByUIDs(array $ctx, \Velmie\Wallet\Users\RequestFullUsersByUIDs $req): \Velmie\Wallet\Users\FullUsersResponse;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetDevicesByUID</code>
     *
     * @throws \Twirp\Error
     */
    public function GetDevicesByUID(array $ctx, \Velmie\Wallet\Users\DevicesRequest $req): \Velmie\Wallet\Users\DevicesResponse;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetByAdministratorClassId</code>
     *
     * @throws \Twirp\Error
     */
    public function GetByAdministratorClassId(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/ValidateTmpAuthToken</code>
     *
     * @throws \Twirp\Error
     */
    public function ValidateTmpAuthToken(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetStaffUsers</code>
     *
     * @throws \Twirp\Error
     */
    public function GetStaffUsers(array $ctx, \Velmie\Wallet\Users\Request $req): \Velmie\Wallet\Users\Response;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/GetCompaniesByIDs</code>
     *
     * @throws \Twirp\Error
     */
    public function GetCompaniesByIDs(array $ctx, \Velmie\Wallet\Users\CompaniesIDsRequest $req): \Velmie\Wallet\Users\CompaniesResponse;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.users.UserHandler/SaveCompaniesByName</code>
     *
     * @throws \Twirp\Error
     */
    public function SaveCompaniesByName(array $ctx, \Velmie\Wallet\Users\CompaniesNameRequest $req): \Velmie\Wallet\Users\CompaniesResponse;
}
