<?php
# Generated by the protocol buffer compiler (protoc-gen-twirp_php ).  DO NOT EDIT!
# source: permissions.proto

declare(strict_types=1);

namespace Velmie\Wallet\Permissions;

/**
 *
 *
 * Generated from protobuf service <code>velmie.wallet.permissions.PermissionChecker</code>
 */
interface PermissionChecker
{
    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.permissions.PermissionChecker/Check</code>
     *
     * @throws \Twirp\Error
     */
    public function Check(array $ctx, \Velmie\Wallet\Permissions\PermissionReq $req): \Velmie\Wallet\Permissions\PermissionResp;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.permissions.PermissionChecker/CheckAll</code>
     *
     * @throws \Twirp\Error
     */
    public function CheckAll(array $ctx, \Velmie\Wallet\Permissions\PermissionsReq $req): \Velmie\Wallet\Permissions\PermissionsResp;

    /**
     *
     *
     * Generated from protobuf method <code>velmie.wallet.permissions.PermissionChecker/GetGroupsByIds</code>
     *
     * @throws \Twirp\Error
     */
    public function GetGroupsByIds(array $ctx, \Velmie\Wallet\Permissions\GroupIdsReq $req): \Velmie\Wallet\Permissions\GroupsResponse;
}
